# Site settings
title: Make Amamzon healthy again!
description: >- # this means to ignore newlines until "baseurl:"
  This page shows the results of a students' project from the <a href="https://dlab.epfl.ch/teaching/fall2019/cs401/">Applied Data Analysis</a> course of <a href="https://www.epfl.ch/">EPFL</a> (Switzerland).

# Contact information
street_address: 1234 Somewhere Road
city: Lausanne
state: VD
zip_code: 1010
country: Switzerland
email: youremailaddress@gmail.com

# Social settings
500px:
  url:
  label: 
facebook:
  url: https://github.com/moodule
  label:
github:
  url: https://github.com/moodule
  label:
gitlab:
  url:
  label:
instagram:
  url: https://github.com/moodule
  label:
linkedin:
  url:
  label:
medium:
  url: https://github.com/moodule
  label:
pinterest:
  url:
  label:
slack:
  url:
  label:
snapchat:
  url: https://github.com/moodule
  label:
twitter:
  url: https://github.com/moodule
  label:

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Collections
collections:
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-seo-tag

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikoro1904.github.io/test" # the base hostname & protocol for your site, e.g. http://example.com
author: hi there
copyright:
  holder: Untitled
  license: CC0

# Exclude from processing
